CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_EXAM11`()
BEGIN
	DECLARE done INT DEFAULT FALSE;
    DECLARE V_DNAME VARCHAR(50);
    DECLARE V_LOC VARCHAR(50);
    DECLARE V_NOP INT;
    DECLARE V_SAL DECIMAL(10,2);
    DECLARE CUR_11 CURSOR FOR SELECT DNAME, LOC, COUNT(EMPNO) AS 'NUMBER OF PEOPLE', ROUND(AVG(SAL),1) AS SALARY
							  FROM EMP RIGHT JOIN DEPT USING(DEPTNO)
                              GROUP BY DNAME, LOC;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
    
    DROP TEMPORARY TABLE IF EXISTS EXAM11;
    CREATE TEMPORARY TABLE EXAM11(
		DNAME VARCHAR(50), LOC VARCHAR(50), NOP INT, SAL DECIMAL(10,1)
    );
    
    OPEN CUR_11;
    READ_LOOP: LOOP
		FETCH CUR_11 INTO V_DNAME,V_LOC,V_NOP,V_SAL;
        IF done THEN
			LEAVE READ_LOOP;
		END IF;
        INSERT INTO EXAM11(DNAME,LOC,NOP,SAL) VALUES(V_DNAME, V_LOC, V_NOP, V_SAL);
    END LOOP;
    CLOSE CUR_11;
END